In [1]:
# %% -*- coding: utf-8 -*-

""" Created on June 12, 2021 // @author: Sarah Shi """

# Import and load Python packages
import os
import numpy as np
import pandas as pd
import PyIRoGlass as pig

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

The VICTOR implementation here aims to get your transmission FTIR spectra processed. We remove degrees of freedom to simplify the process. Examples workflows working with these spectra can be found on the [ReadTheDocs](https://pyiroglass.readthedocs.io/en/latest/).

The files necessary include example transmission FTIR spectra, as well as 'Colab_Binder_ChemThick.CSV' file, containing all chemistry and thickness data. Find an example [here](https://github.com/sarahshi/PyIRoGlass/blob/main/Inputs/COLAB_BINDER/Colab_Binder_ChemThick.csv). Ensure that all of your transmission FTIR spectra names (before the .CSV) match up identically with the sample names in the chemistry and thickness file. This is necessary to ensure that the algorithm can match up samples.

# Load transmission FTIR spectra here:

In [10]:
# Provide folder name containing transmission FTIR spectra
SPEC_PATH = "TransmissionSpectra"

# Load ChemThick.CSV here:

In [11]:
# Provide CSV name for your chemistry and thickness file. Here, it is called Colab_Binder_ChemThick.csv. Modify it here for your file name.
CHEMTHICK_PATH = 'Colab_Binder_ChemThick.csv'

# Run PyIRoGlass here:

In [14]:
# Set the output path name desired for your sample. We will call our output 'RESULTS'.
OUTPUT_PATH = 'RESULTS'

# Load a list of files and a dictionary of transmission FTIR spectra from the files identified earlier.
loader = pig.SampleDataLoader(SPEC_PATH, CHEMTHICK_PATH)
dfs_dict, chem, thick = loader.load_all_data()

# Run PyIRoGlass! df_output will be saved as a CSV called OUTPUT_PATH+'_DF.CSV' in the FINALDATA directory.
df_output, failures = pig.calculate_baselines(dfs_dict, OUTPUT_PATH)

# Default temperature and pressure conditions of analysis are set at 25 C and 1 bar. These are the defaults at LDEO.
# df_conc will be saved as a CSV called OUTPUT_PATH+'_H2OCO2.CSV' in the FINALDATA directory.
df_conc = pig.calculate_concentrations(df_output, chem, thick, OUTPUT_PATH)

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  Multi-core Markov-chain Monte Carlo (mc3).
  Version 3.2.1.
  Copyright (c) 2015-2025 Patricio Cubillos and collaborators.
  mc3 is open-source software under the MIT license (see LICENSE).
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  Warning:
    The number of requested CPUs (4) is >= than the number of
available CPUs (4).  Enforced ncpu to 3.
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Least-squares best-fitting parameters:
  [ 1.10352342e+00 -1.06147087e+00  9.35733627e-01 -9.21115138e-02
  3.00000000e-01  1.42788938e+03  2.88207396e+01  1.09418301e-01
  1.51745559e+03  3.58474255e+01  1.07059542e-01  6.59012777e-01
  1.22070957e-01  1.53688095e-02 -3.11486494e-04  1.23428192e+00]

Yippee Ki Yay Monte Carlo!
Start MCMC chains  (Mon Jun  9 16:28:54 2025)

[:         ]  10.0% completed  (Mon Jun  9 16:29:03 2025)
Out-of-bound Trials:
[   0   41    0   14 9159    0   33   58    0   92   24    0    0    0
    0    0]
Best Parameters: (chisq=369.0163)
[ 1.10352342e+00 -1.06147087e+00  9.35733627e-01 -9.21115138e-02
  3.00000000e-01  1.42788938e+03  2.88207396e+01  1.09418301e-01
  1.51745559e+03  3.58474255e+01  1.07059542e-01  6.59012777e-01
  1.22070957e-01  1.53688095e-02 -3.11486494e-04  1.23428192e+00]

[::        ]  20.0% completed  (Mon Jun  9 16:29:12 2025)
Out-of-bound Trials:
[    0   130     0    22 21682     0    90    64     0  1210    34     0
     0     0     0     0]
Best Parameters: (chisq=369.0163)
[ 1.10352342e+00 -1.06147087e+00  9.35733627e-01 -9.21115138e-02
  3.00000000e-01  1.42788938e+03  2.88207396e+01  1.09418301e-01
  1.51745559e+03  3.58474255e+01  1.07059542e-01  6.59012777e-01
  1.22070957e-01  1.53688095e-02 -3.11486494e-04  1.23428192e+00]
Gelman-Rubin statistics for free parameters:
[1.01347319 1.01512957 1.03393566 1.01075962 1.02590212 1.05398862
 1.0140783  1.01343554 1.01814429 1.05226238 1.00893186 1.02363844
 1.01455154 1.01552443 1.01458791 1.01482076]

[:::       ]  30.0% completed  (Mon Jun  9 16:29:21 2025)
Out-of-bound Trials:
[    0   224     0    45 34749     1   154    69     0  4230    36     0
     0     0     0     0]
Best Parameters: (chisq=369.0163)
[ 1.10352342e+00 -1.06147087e+00  9.35733627e-01 -9.21115138e-02
  3.00000000e-01  1.42788938e+03  2.88207396e+01  1.09418301e-01
  1.51745559e+03  3.58474255e+01  1.07059542e-01  6.59012777e-01
  1.22070957e-01  1.53688095e-02 -3.11486494e-04  1.23428192e+00]
Gelman-Rubin statistics for free parameters:
[1.00270511 1.00314288 1.00241507 1.00260289 1.0035622  1.00481074
 1.00301303 1.0039041  1.0025892  1.0065975  1.00518765 1.00304318
 1.0030666  1.00454052 1.003005   1.00315612]
All parameters converged to within 1% of unity.

[::::      ]  40.0% completed  (Mon Jun  9 16:29:30 2025)
Out-of-bound Trials:
[    0   311     0    60 48010     3   213    71     1  7684    39     0
     0     0     0     0]
Best Parameters: (chisq=369.0163)
[ 1.10352342e+00 -1.06147087e+00  9.35733627e-01 -9.21115138e-02
  3.00000000e-01  1.42788938e+03  2.88207396e+01  1.09418301e-01
  1.51745559e+03  3.58474255e+01  1.07059542e-01  6.59012777e-01
  1.22070957e-01  1.53688095e-02 -3.11486494e-04  1.23428192e+00]
Gelman-Rubin statistics for free parameters:
[1.00171308 1.00206424 1.00116162 1.00118265 1.00110692 1.00114001
 1.00110394 1.00146875 1.00067208 1.00123    1.00091099 1.00179394
 1.00084719 1.00084511 1.00192089 1.00202068]
All parameters converged to within 1% of unity.

[:::::     ]  50.0% completed  (Mon Jun  9 16:29:39 2025)
Out-of-bound Trials:
[    0   438     0    90 61202     3   294    72     1 11471    40     0
     0     0     0     0]
Best Parameters: (chisq=369.0163)
[ 1.10352342e+00 -1.06147087e+00  9.35733627e-01 -9.21115138e-02
  3.00000000e-01  1.42788938e+03  2.88207396e+01  1.09418301e-01
  1.51745559e+03  3.58474255e+01  1.07059542e-01  6.59012777e-01
  1.22070957e-01  1.53688095e-02 -3.11486494e-04  1.23428192e+00]
Gelman-Rubin statistics for free parameters:
[1.00121538 1.00143528 1.000444   1.00075287 1.00090246 1.00135144
 1.00115858 1.00114095 1.00073919 1.00178975 1.00037019 1.00166099
 1.00092938 1.00086846 1.00134027 1.00137751]
All parameters converged to within 1% of unity.

[::::::    ]  60.0% completed  (Mon Jun  9 16:29:48 2025)
Out-of-bound Trials:
[    0   569     0   116 74250     4   366    77     1 15424    42     0
     0     0     0     0]
Best Parameters: (chisq=369.0163)
[ 1.10352342e+00 -1.06147087e+00  9.35733627e-01 -9.21115138e-02
  3.00000000e-01  1.42788938e+03  2.88207396e+01  1.09418301e-01
  1.51745559e+03  3.58474255e+01  1.07059542e-01  6.59012777e-01
  1.22070957e-01  1.53688095e-02 -3.11486494e-04  1.23428192e+00]
Gelman-Rubin statistics for free parameters:
[1.00059227 1.00076289 1.00032329 1.00046963 1.00066996 1.00105375
 1.00055848 1.00118076 1.00085227 1.00182855 1.00055901 1.00157836
 1.0009058  1.00091652 1.00068525 1.00074929]
All parameters converged to within 1% of unity.

All parameters satisfy the GR convergence threshold of 1.01, stopping
the MCMC.

MCMC Summary:
-------------
  Number of evaluated samples:        606430
  Number of parallel chains:               9
  Average iterations per chain:        67381
  Burned-in iterations per chain:      20000
  Thinning factor:                         5
  MCMC sample size (thinned, burned):  85286
  Acceptance rate:   21.11%

Parameter name     best fit   median      1sigma_low   1sigma_hi        S/N
--------------- -----------  -----------------------------------  ---------
B_mean           1.1035e+00   1.1325e+00 -3.3956e-02  4.0207e-02       28.2
B_PC1           -1.0615e+00  -7.6268e-01 -3.6522e-01  4.2882e-01        2.6
B_PC2            9.3573e-01   9.3193e-01 -1.9418e-02  1.9810e-02       47.6
B_PC3           -9.2112e-02  -5.4986e-02 -5.7932e-02  6.2792e-02        1.5
B_PC4            3.0000e-01   2.7871e-01 -3.0069e-02  1.5689e-02       12.1
G1430_peak       1.4279e+03   1.4279e+03 -1.3885e+00  1.4809e+00      994.3
G1430_std        2.8821e+01   2.8792e+01 -1.1829e+00  1.2530e+00       23.5
G1430_amp        1.0942e-01   1.0863e-01 -4.0131e-03  4.1831e-03       26.8
G1515_peak       1.5175e+03   1.5176e+03 -1.5489e+00  1.5376e+00      993.9
G1515_std        3.5847e+01   3.6057e+01 -2.1075e+00  2.1891e+00       17.8
G1515_amp        1.0706e-01   1.0699e-01 -3.6250e-03  3.5613e-03       29.8
H1635_mean       6.5901e-01   6.5927e-01 -3.0829e-03  3.0768e-03      214.1
H1635_PC1        1.2207e-01   1.1994e-01 -1.3946e-02  1.4315e-02        8.6
H1635_PC2        1.5369e-02   1.5041e-02 -2.1892e-02  2.2018e-02        0.7
m               -3.1149e-04  -2.6071e-04 -6.1818e-05  7.2619e-05        4.4
b                1.2343e+00   1.2192e+00 -2.2853e-02  1.9694e-02       56.0

  Best-parameter's chi-squared:       367.5930
  Best-parameter's -2*log(posterior): 369.0163
  Bayesian Information Criterion:     469.8369
  Reduced chi-squared:                  0.6338
  Standard deviation of residuals:  0.00785345

For a detailed summary with all parameter posterior statistics see
/home/jovyan/PyIroglass/NPZTXTFILES/RESULTS/AC4_OL49_021920_30x30_H2O_a_statistics.txt

Output sampler files:
  /home/jovyan/PyIroglass/NPZTXTFILES/RESULTS/AC4_OL49_021920_30x30_H2O_a_statistics.txt
  /home/jovyan/PyIroglass/NPZTXTFILES/RESULTS/AC4_OL49_021920_30x30_H2O_a.npz
  /home/jovyan/PyIroglass/LOGFILES/RESULTS/AC4_OL49_021920_30x30_H2O_a.log

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  Multi-core Markov-chain Monte Carlo (mc3).
  Version 3.2.1.
  Copyright (c) 2015-2025 Patricio Cubillos and collaborators.
  mc3 is open-source software under the MIT license (see LICENSE).
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  Warning:
    The number of requested CPUs (4) is >= than the number of
available CPUs (4).  Enforced ncpu to 3.
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Least-squares best-fitting parameters:
  [ 1.13316739e+00 -9.45341687e-01  8.76245843e-01 -3.78017564e-02
  3.00000000e-01  1.42798697e+03  2.91059696e+01  1.12291145e-01
  1.51785343e+03  3.62248155e+01  1.10034283e-01  6.56779294e-01
  1.04013218e-01  2.94750314e-02 -2.95932984e-04  1.22983946e+00]

Yippee Ki Yay Monte Carlo!
Start MCMC chains  (Mon Jun  9 16:30:11 2025)

[:         ]  10.0% completed  (Mon Jun  9 16:30:20 2025)
Out-of-bound Trials:
[    0     0     0     0 10759     0     1    51     0    11    14     0
     0     0     0     0]
Best Parameters: (chisq=309.1976)
[ 1.13316739e+00 -9.45341687e-01  8.76245843e-01 -3.78017564e-02
  3.00000000e-01  1.42798697e+03  2.91059696e+01  1.12291145e-01
  1.51785343e+03  3.62248155e+01  1.10034283e-01  6.56779294e-01
  1.04013218e-01  2.94750314e-02 -2.95932984e-04  1.22983946e+00]

[::        ]  20.0% completed  (Mon Jun  9 16:30:29 2025)
Out-of-bound Trials:
[    0     5     0     0 19640     0     6    53     0  1573    15     0
     0     0     0     0]
Best Parameters: (chisq=309.1976)
[ 1.13316739e+00 -9.45341687e-01  8.76245843e-01 -3.78017564e-02
  3.00000000e-01  1.42798697e+03  2.91059696e+01  1.12291145e-01
  1.51785343e+03  3.62248155e+01  1.10034283e-01  6.56779294e-01
  1.04013218e-01  2.94750314e-02 -2.95932984e-04  1.22983946e+00]
Gelman-Rubin statistics for free parameters:
[1.08895977 1.08695354 1.01585614 1.08228439 1.07208532 1.01320651
 1.00535922 1.00674249 1.00954211 1.01619643 1.02826519 1.0094213
 1.01625749 1.01377829 1.08650884 1.08287981]

[:::       ]  30.0% completed  (Mon Jun  9 16:30:39 2025)
Out-of-bound Trials:
[    0    45     0    14 29542     1    31    53     0  4944    15     0
     0     0     0     0]
Best Parameters: (chisq=309.1976)
[ 1.13316739e+00 -9.45341687e-01  8.76245843e-01 -3.78017564e-02
  3.00000000e-01  1.42798697e+03  2.91059696e+01  1.12291145e-01
  1.51785343e+03  3.62248155e+01  1.10034283e-01  6.56779294e-01
  1.04013218e-01  2.94750314e-02 -2.95932984e-04  1.22983946e+00]
Gelman-Rubin statistics for free parameters:
[1.00906758 1.00850862 1.00381332 1.00898429 1.00833268 1.00250255
 1.00252978 1.00614016 1.00217974 1.00410645 1.00637277 1.00230477
 1.00161196 1.00591833 1.00885924 1.00851257]
All parameters converged to within 1% of unity.

[::::      ]  40.0% completed  (Mon Jun  9 16:30:48 2025)
Out-of-bound Trials:
[    0    97     0    29 40809     2    66    55     0  8903    17     0
     0     0     0     0]
Best Parameters: (chisq=309.1976)
[ 1.13316739e+00 -9.45341687e-01  8.76245843e-01 -3.78017564e-02
  3.00000000e-01  1.42798697e+03  2.91059696e+01  1.12291145e-01
  1.51785343e+03  3.62248155e+01  1.10034283e-01  6.56779294e-01
  1.04013218e-01  2.94750314e-02 -2.95932984e-04  1.22983946e+00]
Gelman-Rubin statistics for free parameters:
[1.00624773 1.00590979 1.00156694 1.00527671 1.00547076 1.00093236
 1.00215708 1.00387018 1.00185418 1.00282504 1.00290417 1.00212102
 1.0006943  1.00315898 1.00611752 1.00582642]
All parameters converged to within 1% of unity.

[:::::     ]  50.0% completed  (Mon Jun  9 16:30:57 2025)
Out-of-bound Trials:
[    0   181     0    50 52761     3   109    56     0 13348    18     0
     0     0     0     0]
Best Parameters: (chisq=309.1976)
[ 1.13316739e+00 -9.45341687e-01  8.76245843e-01 -3.78017564e-02
  3.00000000e-01  1.42798697e+03  2.91059696e+01  1.12291145e-01
  1.51785343e+03  3.62248155e+01  1.10034283e-01  6.56779294e-01
  1.04013218e-01  2.94750314e-02 -2.95932984e-04  1.22983946e+00]
Gelman-Rubin statistics for free parameters:
[1.00378711 1.00361492 1.00116528 1.00320605 1.00325094 1.00069564
 1.00107667 1.00250083 1.00082609 1.00174813 1.00210348 1.00128634
 1.00036557 1.00136941 1.00369932 1.00351044]
All parameters converged to within 1% of unity.

[::::::    ]  60.0% completed  (Mon Jun  9 16:31:06 2025)
Out-of-bound Trials:
[    0   262     0    72 65026     4   155    56     0 17837    18     0
     0     0     0     0]
Best Parameters: (chisq=309.1976)
[ 1.13316739e+00 -9.45341687e-01  8.76245843e-01 -3.78017564e-02
  3.00000000e-01  1.42798697e+03  2.91059696e+01  1.12291145e-01
  1.51785343e+03  3.62248155e+01  1.10034283e-01  6.56779294e-01
  1.04013218e-01  2.94750314e-02 -2.95932984e-04  1.22983946e+00]
Gelman-Rubin statistics for free parameters:
[1.00329122 1.00322907 1.00084058 1.00281135 1.00206122 1.00026119
 1.000875   1.0015768  1.00074569 1.0007804  1.00145794 1.00125831
 1.00046709 1.00067204 1.00322117 1.00312359]
All parameters converged to within 1% of unity.

All parameters satisfy the GR convergence threshold of 1.01, stopping
the MCMC.

MCMC Summary:
-------------
  Number of evaluated samples:        605865
  Number of parallel chains:               9
  Average iterations per chain:        67318
  Burned-in iterations per chain:      20000
  Thinning factor:                         5
  MCMC sample size (thinned, burned):  85173
  Acceptance rate:   22.87%

Parameter name     best fit   median      1sigma_low   1sigma_hi        S/N
--------------- -----------  -----------------------------------  ---------
B_mean           1.1332e+00   1.1593e+00 -3.3231e-02  3.8918e-02       31.0
B_PC1           -9.4534e-01  -6.7811e-01 -3.5819e-01  4.1187e-01        2.4
B_PC2            8.7625e-01   8.7285e-01 -1.9565e-02  1.9674e-02       44.5
B_PC3           -3.7802e-02  -5.2417e-03 -5.6350e-02  6.2307e-02        0.6
B_PC4            3.0000e-01   2.8086e-01 -2.7636e-02  1.4166e-02       13.6
G1430_peak       1.4280e+03   1.4280e+03 -1.3532e+00  1.4778e+00     1016.2
G1430_std        2.9106e+01   2.9090e+01 -1.1424e+00  1.2251e+00       24.5
G1430_amp        1.1229e-01   1.1158e-01 -4.0227e-03  4.1882e-03       27.4
G1515_peak       1.5179e+03   1.5180e+03 -1.5637e+00  1.5253e+00      989.2
G1515_std        3.6225e+01   3.6407e+01 -2.1003e+00  2.0239e+00       18.9
G1515_amp        1.1003e-01   1.0999e-01 -3.5979e-03  3.5985e-03       30.6
H1635_mean       6.5678e-01   6.5697e-01 -3.0611e-03  3.1784e-03      211.8
H1635_PC1        1.0401e-01   1.0188e-01 -1.4365e-02  1.4326e-02        7.2
H1635_PC2        2.9475e-02   2.8861e-02 -2.1744e-02  2.2124e-02        1.4
m               -2.9593e-04  -2.5030e-04 -6.1201e-05  6.9842e-05        4.5
b                1.2298e+00   1.2164e+00 -2.1766e-02  1.9437e-02       59.0

  Best-parameter's chi-squared:       307.6156
  Best-parameter's -2*log(posterior): 309.1976
  Bayesian Information Criterion:     409.8595
  Reduced chi-squared:                  0.5304
  Standard deviation of residuals:  0.00718424

For a detailed summary with all parameter posterior statistics see
/home/jovyan/PyIroglass/NPZTXTFILES/RESULTS/AC4_OL49_021920_30x30_H2O_b_statistics.txt

Output sampler files:
  /home/jovyan/PyIroglass/NPZTXTFILES/RESULTS/AC4_OL49_021920_30x30_H2O_b_statistics.txt
  /home/jovyan/PyIroglass/NPZTXTFILES/RESULTS/AC4_OL49_021920_30x30_H2O_b.npz
  /home/jovyan/PyIroglass/LOGFILES/RESULTS/AC4_OL49_021920_30x30_H2O_b.log

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  Multi-core Markov-chain Monte Carlo (mc3).
  Version 3.2.1.
  Copyright (c) 2015-2025 Patricio Cubillos and collaborators.
  mc3 is open-source software under the MIT license (see LICENSE).
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  Warning:
    The number of requested CPUs (4) is >= than the number of
available CPUs (4).  Enforced ncpu to 3.
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Least-squares best-fitting parameters:
  [ 1.11834251e+00 -1.31629853e+00  8.38364983e-01 -8.28464370e-02
  3.00000000e-01  1.42835524e+03  2.86911826e+01  1.10144179e-01
  1.51752182e+03  3.54736774e+01  1.10356829e-01  6.60176917e-01
  9.74598884e-02  3.72962658e-02 -3.57253253e-04  1.25351964e+00]

Yippee Ki Yay Monte Carlo!
Start MCMC chains  (Mon Jun  9 16:31:29 2025)

[:         ]  10.0% completed  (Mon Jun  9 16:31:38 2025)
Out-of-bound Trials:
[   0    3    0    0 9199    0    0   31    0    0    3    0    0    0
    0    0]
Best Parameters: (chisq=318.2769)
[ 1.11834251e+00 -1.31629853e+00  8.38364983e-01 -8.28464370e-02
  3.00000000e-01  1.42835524e+03  2.86911826e+01  1.10144179e-01
  1.51752182e+03  3.54736774e+01  1.10356829e-01  6.60176917e-01
  9.74598884e-02  3.72962658e-02 -3.57253253e-04  1.25351964e+00]

[::        ]  20.0% completed  (Mon Jun  9 16:31:47 2025)
Out-of-bound Trials:
[    0    34     0     5 19333     0     9    32     0  1009     5     0
     0     0     0     0]
Best Parameters: (chisq=318.2769)
[ 1.11834251e+00 -1.31629853e+00  8.38364983e-01 -8.28464370e-02
  3.00000000e-01  1.42835524e+03  2.86911826e+01  1.10144179e-01
  1.51752182e+03  3.54736774e+01  1.10356829e-01  6.60176917e-01
  9.74598884e-02  3.72962658e-02 -3.57253253e-04  1.25351964e+00]
Gelman-Rubin statistics for free parameters:
[1.02059226 1.01779397 1.02001186 1.01945394 1.03184121 1.06803392
 1.07034697 1.02118924 1.03655209 1.07973875 1.02428135 1.01868039
 1.01648775 1.02459799 1.01779392 1.01623676]

[:::       ]  30.0% completed  (Mon Jun  9 16:31:57 2025)
Out-of-bound Trials:
[    0    85     0    11 31289     0    40    34     0  3220     5     0
     0     0     0     0]
Best Parameters: (chisq=318.2769)
[ 1.11834251e+00 -1.31629853e+00  8.38364983e-01 -8.28464370e-02
  3.00000000e-01  1.42835524e+03  2.86911826e+01  1.10144179e-01
  1.51752182e+03  3.54736774e+01  1.10356829e-01  6.60176917e-01
  9.74598884e-02  3.72962658e-02 -3.57253253e-04  1.25351964e+00]
Gelman-Rubin statistics for free parameters:
[1.00474992 1.00475009 1.00094414 1.00341972 1.00357105 1.00282422
 1.00593924 1.00109911 1.00302685 1.00278499 1.00091757 1.00396746
 1.00535103 1.00032444 1.00479635 1.00449257]
All parameters converged to within 1% of unity.

[::::      ]  40.0% completed  (Mon Jun  9 16:32:06 2025)
Out-of-bound Trials:
[    0   197     0    27 44004     2   100    35     0  6068     6     0
     0     0     0     0]
Best Parameters: (chisq=318.2769)
[ 1.11834251e+00 -1.31629853e+00  8.38364983e-01 -8.28464370e-02
  3.00000000e-01  1.42835524e+03  2.86911826e+01  1.10144179e-01
  1.51752182e+03  3.54736774e+01  1.10356829e-01  6.60176917e-01
  9.74598884e-02  3.72962658e-02 -3.57253253e-04  1.25351964e+00]
Gelman-Rubin statistics for free parameters:
[1.0019316  1.00157068 1.00113202 1.00156553 1.00237989 1.00288238
 1.00311495 1.00139267 1.00303571 1.00222833 1.00109516 1.00234148
 1.00150613 1.00119083 1.00163839 1.00138653]
All parameters converged to within 1% of unity.

[:::::     ]  50.0% completed  (Mon Jun  9 16:32:15 2025)
Out-of-bound Trials:
[    0   287     0    43 56943     3   154    38     1  9096     7     0
     0     0     0     0]
Best Parameters: (chisq=318.2769)
[ 1.11834251e+00 -1.31629853e+00  8.38364983e-01 -8.28464370e-02
  3.00000000e-01  1.42835524e+03  2.86911826e+01  1.10144179e-01
  1.51752182e+03  3.54736774e+01  1.10356829e-01  6.60176917e-01
  9.74598884e-02  3.72962658e-02 -3.57253253e-04  1.25351964e+00]
Gelman-Rubin statistics for free parameters:
[1.00109677 1.00111408 1.00048837 1.001261   1.00097573 1.00156757
 1.00188723 1.00123249 1.00226651 1.00139634 1.00114512 1.00152828
 1.00105897 1.00093258 1.00104993 1.0010563 ]
All parameters converged to within 1% of unity.

[::::::    ]  60.0% completed  (Mon Jun  9 16:32:23 2025)
Out-of-bound Trials:
[    0   415     0    71 69585     4   228    41     1 12262     8     0
     0     0     0     0]
Best Parameters: (chisq=318.2769)
[ 1.11834251e+00 -1.31629853e+00  8.38364983e-01 -8.28464370e-02
  3.00000000e-01  1.42835524e+03  2.86911826e+01  1.10144179e-01
  1.51752182e+03  3.54736774e+01  1.10356829e-01  6.60176917e-01
  9.74598884e-02  3.72962658e-02 -3.57253253e-04  1.25351964e+00]
Gelman-Rubin statistics for free parameters:

# Display results here:

In [15]:
display(df_output)

,PH_3550_M,PH_3550_STD,H2Ot_3550_MAX,BL_H2Ot_3550_MAX,H2Ot_3550_SAT,PH_1635_BP,PH_1635_STD,PH_1515_BP,PH_1515_STD,P_1515_BP,...,PC4_BP,PC4_STD,m_BP,m_STD,b_BP,b_STD,PH_1635_PC1_BP,PH_1635_PC1_STD,PH_1635_PC2_BP,PH_1635_PC2_STD
AC4_OL49_021920_30x30_H2O_a,2.17225,0.002212,2.649837,0.459859,*,0.659013,0.003078,0.107060,0.003590,1517.455586,...,0.300000,0.024858,-0.000311,0.000070,1.234282,0.022038,0.122071,0.014214,0.015369,0.021746
AC4_OL49_021920_30x30_H2O_b,2.133883,0.002154,2.593884,0.454886,*,0.656779,0.003100,0.110034,0.003595,1517.853427,...,0.300000,0.022139,-0.000296,0.000066,1.229839,0.020845,0.104013,0.014350,0.029475,0.021809
AC4_OL49_021920_30x30_H2O_c,2.163828,0.002194,2.618767,0.452842,*,0.660177,0.003071,0.110357,0.003582,1517.521816,...,0.300000,0.017535,-0.000357,0.000060,1.253520,0.019244,0.097460,0.014317,0.037296,0.021845
AC4_OL53_101220_256s_30x30_a,1.523343,0.003309,1.631044,0.135541,-,0.300627,0.003133,0.053113,0.003682,1519.241535,...,0.227844,0.042881,-0.000446,0.000077,0.721456,0.023196,-0.039099,0.014585,0.052906,0.018497
AC4_OL53_101220_256s_30x30_b,1.520079,0.003162,1.651256,0.136552,-,0.299651,0.003083,0.052885,0.003723,1519.069491,...,0.210480,0.044650,-0.000410,0.000082,0.713051,0.024800,-0.039981,0.014607,0.051994,0.018569
AC4_OL53_101220_256s_30x30_c,1.515344,0.002909,1.646292,0.136839,-,0.301805,0.003056,0.054714,0.003639,1519.069487,...,0.233336,0.037418,-0.000461,0.000061,0.724729,0.018459,-0.045782,0.014589,0.059467,0.018475
STD_D1010_012821_256s_100x100_a,2.710894,0.001587,2.915508,0.206641,*,0.173135,0.003050,0.075928,0.003394,1522.799669,...,0.177129,0.023558,-0.000233,0.000014,2.462710,0.006425,0.066857,0.014383,-0.037754,0.023344
STD_D1010_012821_256s_100x100_b,2.799156,0.001465,3.012166,0.21019,*,0.222366,0.002815,0.106212,0.002399,1520.451148,...,0.039924,0.014877,-0.000782,0.000004,2.748642,0.001233,-0.175681,0.013052,0.192248,0.015995
STD_D1010_012821_256s_100x100_c,2.830031,0.001568,3.0087,0.205826,*,0.228988,0.003045,0.108127,0.002786,1520.834307,...,-0.088648,0.015752,-0.000647,0.000008,2.679220,0.004025,-0.209593,0.014333,0.230021,0.017775

In [16]:
display(df_conc)

,H2Ot_MEAN,H2Ot_STD,H2Ot_3550_M,H2Ot_3550_STD,H2Ot_3550_SAT,H2Om_1635_BP,H2Om_1635_STD,CO2_MEAN,CO2_STD,CO2_1515_BP,...,epsilon_H2Ot_3550,sigma_epsilon_H2Ot_3550,epsilon_H2Om_1635,sigma_epsilon_H2Om_1635,epsilon_CO2,sigma_epsilon_CO2,epsilon_H2Om_5200,sigma_epsilon_H2Om_5200,epsilon_OH_4500,sigma_epsilon_OH_4500
AC4_OL49_021920_30x30_H2O_a,2.545209,0.160677,2.4206,0.189575,*,1.301434,0.189825,753.184415,36.540335,745.9116,...,66.142594,7.503769,37.322108,8.645060,258.429949,18.362798,1.009458,0.300803,0.861196,0.279571
AC4_OL49_021920_30x30_H2O_b,2.367323,0.146333,2.373696,0.185924,*,1.294759,0.188972,773.19699,37.261574,765.298956,...,66.142594,7.503769,37.322108,8.645060,258.429949,18.362798,1.009458,0.300803,0.861196,0.279571
AC4_OL49_021920_30x30_H2O_c,2.534323,0.160467,2.410958,0.188682,*,1.303594,0.190265,767.109646,37.058703,768.802647,...,66.142594,7.503769,37.322108,8.645060,258.429949,18.362798,1.009458,0.300803,0.861196,0.279571
AC4_OL53_101220_256s_30x30_a,4.036918,0.432587,4.036918,0.432587,-,1.49134,0.258511,737.553146,62.132009,756.185931,...,64.493655,7.380834,34.452486,8.504269,293.261300,16.287120,0.901474,0.295829,0.779611,0.274924
AC4_OL53_101220_256s_30x30_b,4.027910,0.431421,4.02791,0.431421,-,1.486367,0.257387,733.762236,61.960505,752.870408,...,64.493655,7.380834,34.452486,8.504269,293.261300,16.287120,0.901474,0.295829,0.779611,0.274924
AC4_OL53_101220_256s_30x30_c,4.014841,0.429986,4.014841,0.429986,-,1.496858,0.259467,750.003787,62.115607,778.807828,...,64.493655,7.380834,34.452486,8.504269,293.261300,16.287120,0.901474,0.295829,0.779611,0.274924
STD_D1010_012821_256s_100x100_a,0.903953,0.096941,1.201405,0.087966,*,0.153236,0.025394,157.114814,7.322059,165.492165,...,62.751984,7.251813,31.421482,8.354348,311.700491,15.127604,0.787418,0.290510,0.693438,0.270004
STD_D1010_012821_256s_100x100_b,0.944457,0.096772,1.241057,0.090825,*,0.196895,0.03253,180.832821,6.883724,231.600732,...,62.751984,7.251813,31.421482,8.354348,311.700491,15.127604,0.787418,0.290510,0.693438,0.270004
STD_D1010_012821_256s_100x100_c,0.932551,0.094623,1.254587,0.091801,*,0.202732,0.033496,186.466416,7.220135,235.745971,...,62.751984,7.251813,31.421482,8.354348,311.700491,15.127604,0.787418,0.290510,0.693438,0.270004